### PR TITLE
Dannydev/paper

### PR DESCRIPTION
**Pull request by DannyHinshaw**
@jleonelion , here is the branch with the latest version of gdax-tt master merged in and the compiler errors fixed. From our conversation in the gdax-tt issues it seemed like maybe you were done with this feature (or at least the current iteration) other than fixing those issues above? I know there are still some todo-_like_ and unfinished _looking_ features in the code, is there anything else in particular you wanted done or anything other directions you'd like to give me on getting this wrapped up? I haven't been able to dig into actually testing the features yet (I'll have the time sometime this week), but I figured I could go ahead and put this out there to get the ball running.

If it's ok with you, let's leave this PR open until we're ready to submit the paper-trading feature PR to the gdax-tt repo, this way we can keep relative conversations in one place along with any other feature repo history.

### CODE REVIEW

**Comment by DannyHinshaw** [comment]
@jleonelion I just ran the `paperTraderDemo.ts` and it immediately comes to a stand still with

```
...
error: The websocket feed to wss://ws-feed.gdax.com  has reported an error. If necessary, we will reconnect
...
```

~~I'm pretty sure this is from trying to use the api unauthenticated. I think it may be better to use the sandbox api to test if we want the demo to not use real money/coin/accounts. The sandbox api is pretty shoddy imo, but worth a shot for testing this demo. We can then use the env variables for credentials similar to the `traderDemo.ts`. ie for sandbox api config~~

**Comment by DannyHinshaw** [comment]
Turns out the "websocket" error was unrelated to the actual api implementation. It had to do with the if/else logic for the `positionDelta`, namely checking for properties on an `undefined` instance of `positionDelta`. I fixed this with some guards. However, I'm still a little unclear on how the logic should operate in the first if statement. If you care to clear that up it would help, otherwise I'll just keep debugging. Basically it looks like this...

```
if (positionDelta === undefined && trader.state().orderPool && trader.state().asks.length > 0) {
```

should be more like this (`JSON.stringify` check for empty object is just a hack for now):

```
if (positionDelta === undefined && JSON.stringify(trader.state().orderPool) === '{}' && !trader.state().asks.length) {
```

Does that seem right? Again, not really sure on this strategy.

Anyway, if so, running with the current fixes now gets some action going in terminal logs. However, after the first trades are executed it produces an orderbook balancing error (or so it looks like). Something like this where I'm logging the `positionDelta` and of course, the price is always different:

```
2018-05-09T00:22:33.132Z - info: Trade executed {"type":"tradeExecuted","productId":"BTC-USD","orderId":"919e2fe4-2cd5-99ab-c759-af2581be613e","side":"sell","price":"9127.37000000","orderType":"limit","tradeSize":"1","remainingSize":"0","time":"2018-05-09T00:22:33.132Z"}
2018-05-09T00:22:33.135Z - info: Trade finalized {"type":"tradeFinalized","productId":"BTC-USD","orderId":"919e2fe4-2cd5-99ab-c759-af2581be613e","side":"sell","price":"9127.37000000","remainingSize":"0","time":"2018-05-09T00:22:33.134Z","reason":"limit order triggered by trade price"}
positionDelta:: BigNumber { s: -1, e: 0, c: [ 1 ] }
2018-05-09T00:22:36.175Z - info: Trade executed {"type":"tradeExecuted","productId":"BTC-USD","orderId":"08e6796d-caa9-78f3-f20c-b8bfae3de45d","side":"sell","price":"9128.50000000","orderType":"limit","tradeSize":"1","remainingSize":"0","time":"2018-05-09T00:22:36.175Z"}
2018-05-09T00:22:36.176Z - info: Trade finalized {"type":"tradeFinalized","productId":"BTC-USD","orderId":"08e6796d-caa9-78f3-f20c-b8bfae3de45d","side":"sell","price":"9128.50000000","remainingSize":"0","time":"2018-05-09T00:22:36.176Z","reason":"limit order triggered by trade price"}
2018-05-09T00:22:36.176Z - error: Total size should be zero at level $9124.91 but was 2.
2018-05-09T00:22:36.177Z - info: Order placed {"price":"9127.5","size":"1","side":"buy","id":"80737374-6e6e-03a5-889d-267a99179ce4","time":"2018-05-09T00:22:36.175Z","productId":"BTC-USD","status":"Pending","extra":{"type":"placeOrder","time":"2018-05-09T00:22:36.175Z","productId":"BTC-USD","price":"9127.5","size":"1","side":"buy","orderType":"limit"}}
positionDelta:: BigNumber { s: -1, e: 0, c: [ 2 ] }
positionDelta:: BigNumber { s: -1, e: 0, c: [ 2 ] }
positionDelta:: BigNumber { s: -1, e: 0, c: [ 2 ] }
```

**Comment by jleonelion** [comment]
It looks like you have been doing a lot @DannyHinshaw 

I'll be honest, I am not the most adept at Github.  I accepted your pull request through the web interface, and it looks like I was able to get the changes in that branch on my local system.  However, I have compile errors so I'm not confident everything came together.

For example
`src/exchanges/ccxt/index.ts(36,27): error TS2339: Property 'bibox' does not exist on type 'typeof 'ccxt''.`

Anyways, can you clarify what aspect of the if statement was not working?  Are you familiar with "straddles" and "delta neutral" concepts in trading?

**Comment by DannyHinshaw** [comment]
@jleonelion hey, I am very new to trading, this is part of my learning experience so I'm not familiar with those concepts. 

I'm not sure if there is anything wrong with that if statement, but the way it was formatted nothing ever happened when I ran the demo. Everything ended up in the swallowed `else` statement at the end of the chain. Maybe this was intended? That's the main question, is I'm just not sure what you're logic is for this strategy.

As to the compile error, that is strange. I'll try doing a fresh branch merge later today and see if we can get that resolved.

**Comment by DannyHinshaw** [comment]
@jleonelion hey, curious as to your process for testing when you get those compiler errors. I just went through the following (in a fresh directory):

```
git clone https://github.com/jleonelion/gdax-tt.git 
```

```
cd gdax-tt && yarn install && yarn test
```
 
All tests are passing successfully here with no errors. Did you run `git pull` before you tested the latest changes? Maybe try a fresh install like I did above?

**Comment by DannyHinshaw** [comment]
@jleonelion what else needs done to get this merged up?

**Pull request merged**
